In [388]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
mpl.style.use('ggplot')

In [389]:
car = pd.read_csv(r"C:\Users\HP\Desktop\prj\quikr_car.csv")

In [390]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [391]:
car.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [392]:
car.isnull().sum()[car.isnull().sum()>0]

kms_driven    52
fuel_type     55
dtype: int64

In [393]:
car.isna().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [394]:
car.shape

(892, 6)

In [395]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

Quality
--> 
names are pretty inconsistent--> 
names have company names attached to i--> t
some names are spam like 'Maruti Ertiga showroom condition with' and 'Well mentained Tata Sum--> o'
company: many of the names are not of any company like 'Used', 'URJENT', and sor-->  Price
Price has commas in its prices and is in-->  object
kms_driven has object values with kms --> at last.
It has nan values and two rows have 'Petrol--> ' in them
fuel_type has nan values

# Cleaning Data

In [396]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [397]:
# car=car[car['year'].str.isnumeric()]  # year has many non-year values

In [398]:
# car['year']=car['year'].astype(int) # year is in object. Change to integer

In [399]:
car['Price'].unique()   # 'Ask for price' is not value --> Price has Ask for Price

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [400]:
car['kms_driven'].unique()  # kms_driven has kms with interger , kms driven object to integer , kms_driven has nan values

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [401]:
car['fuel_type'].unique() # it has ha nan values

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [402]:
car['company'].unique()

array(['Hyundai', 'Mahindra', 'Maruti', 'Ford', 'Skoda', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'I', 'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat',
       'Commercial', 'MARUTI', 'Force', 'Mercedes', 'Land', 'Yamaha',
       'selling', 'URJENT', 'Swift', 'Used', 'Jaguar', 'Jeep', 'tata',
       'Sale', 'very', 'Volvo', 'i', '2012', 'Well', 'all', '7', '9',
       'scratch', 'urgent', 'sell', 'TATA', 'Any', 'Tara'], dtype=object)

In [403]:
car['name'].unique() # we will keep first three words of name

array(['Hyundai Santro Xing XO eRLX Euro III', 'Mahindra Jeep CL550 MDI',
       'Maruti Suzuki Alto 800 Vxi',
       'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi', 'Ford Figo', 'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
       'Maruti Suzuki Alto K10 VXi AMT', 'Skoda Fabia Classic 1.2 MPI',
       'Maruti Suzuki Stingray VXi', 'Hyundai Elite i20 Magna 1.2',
       'Mahindra Scorpio SLE BS IV', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Maruti Suzuki Alto 800',
       'Hyundai i20 Sportz 1.2', 'Maruti Suzuki Alto 800 Lx',
       'Maruti Suzuki Vitara Brezza ZDi', 'Maruti Suzuki Alto LX',
       'Mahindra Bolero DI', 'Maruti Suzuki Swift Dzire ZDi',
       'Mahindra Scorpio S10 4WD', 'Maruti Suzuki Swift Vdi BSIII',
       'Maruti Suzuki Wagon R VXi BS III',
       'Maruti Suzuki Wagon R VXi Minor',
       'Toyota Innova 2.0 G 8 STR BS IV', 'Renault Lodgy 85 PS RXL',
       'Skoda Yeti Ambition 2.0 TDI CR 4x2',
       'Maruti Suzuki Baleno Delta 1.2',
       'Renault Duster 110 PS RxZ Diesel Plus',
       'Renault Duster 85 PS RxE Diesel', 'Honda City 1.5 S MT',
       'Maruti Suzuki Dzire', 'Honda Amaze', 'Honda Amaze 1.5 SX i DTEC',
       'Honda City', 'Datsun Redi GO S', 'Maruti Suzuki SX4 ZXI MT',
       'Mitsubishi Pajero Sport Limited Edition',
       'Maruti Suzuki Swift VXi 1.2 ABS BS IV', 'Honda City ZX CVT',
       'Maruti Suzuki Wagon R LX BS IV', 'Tata Indigo eCS LS CR4 BS IV',
       'Volkswagen Polo Highline Exquisite P',
       'I want to sell my car Tata Zest', 'Chevrolet Spark LS 1.0',
       'Renault Duster 110PS Diesel RxZ', 'Mini Cooper S 1.6',
       'Skoda Fabia 1.2L Diesel Ambiente', 'Renault Duster',
       'Mahindra Scorpio S4', 'Mahindra Scorpio VLX 2WD BS IV',
       'Mahindra Quanto C8', 'Ford EcoSport', 'Honda Brio',
       'Volkswagen Vento Highline Plus 1.5 Diesel AT',
       'Hyundai i20 Magna', 'Toyota Corolla Altis Diesel D4DG',
       'Hyundai Verna Transform SX VTVT',
       'Toyota Corolla Altis Petrol Ltd', 'Honda City 1.5 EXi New',
       'Skoda Fabia 1.2L Diesel Elegance', 'BMW 3 Series 320i',
       'Maruti Suzuki A Star Lxi', 'Toyota Etios GD',
       'Ford Figo Diesel EXI Option',
       'Maruti Suzuki Swift Dzire VXi 1.2 BS IV',
       'Chevrolet Beat LT Diesel', 'BMW 7 Series 740Li Sedan',
       'Mahindra XUV500 W8 AWD 2013', 'Hyundai i10 Magna 1.2',
       'Hyundai Verna Fluidic New', 'Maruti Suzuki Swift VXi 1.2 BS IV',
       'Maruti Suzuki Ertiga ZXI Plus', 'Maruti Suzuki Ertiga Vxi',
       'Maruti Suzuki Ertiga VDi', 'Maruti Suzuki Alto LXi BS III',
       'Hyundai Grand i10 Asta 1.1 CRDi', 'Honda Amaze 1.2 S i VTEC',
       'Hyundai i20 Asta 1.4 CRDI 6 Speed', 'Ford Figo Diesel EXI',
       'Maruti Suzuki Eeco 5 STR WITH AC HTR', 'Maruti Suzuki Ertiga ZXi',
       'Maruti Suzuki Esteem LXi BS III', 'Maruti Suzuki Ritz VXI',
       'Maruti Suzuki Ritz LDi', 'Maruti Suzuki Dzire VDI',
       'Toyota Etios Liva G', 'Hyundai i20 Sportz 1.4 CRDI',
       'Chevrolet Spark', 'Nissan Micra XV', 'Maruti Suzuki Swift',
       'Honda Amaze 1.5 S i DTEC', 'Chevrolet Beat', 'Toyota Corolla',
       'Honda City 1.5 V MT', 'Ford EcoSport Trend 1.5L TDCi',
       'Hyundai i20 Asta 1.2', 'Tata Indica V2 eLS',
       'Maruti Suzuki Alto 800 Lxi', 'Hindustan Motors Ambassador',
       'Toyota Corolla Altis 1.8 GL', 'Toyota Corolla Altis 1.8 J',
       'Toyota Innova 2.5 GX BS IV 7 STR',
       'Volkswagen Jetta Highline TDI AT',
       'Volkswagen Polo Comfortline 1.2L P', 'Volkswagen Polo',
       'Mahindra Scorpio', 'Nissan Sunny', 'Hyundai Elite i20',
       'Renault Kwid', 'Mahindra Scorpio VLX Airbag',
       'Chevrolet Spark LT 1.0', 'Datsun Redi GO T O',
       'Maruti Suzuki Swift RS VDI', 'Fiat Punto Emotion 1.2',
       'Hyundai i10 Sportz 1.2', 'Chevrolet Beat LT Opt Diesel',
       'Chevrolet Beat LS Diesel', 'Tata Indigo CS',
       'Maruti Suzuki Swift VDi', 'Hyundai Eon Era Plus',
       'Mahindra XUV500', 'Ford Fiesta', 'Maruti Suzuki Wagon R',
       'Hyundai i20', 'Tata Indigo eCS LX TDI BS III',
       'Hyundai Fluidic Verna 1.6 CRDi SX',
       'Commercial , DZire LDI, 2016, for sale', 'Fiat Petra ELX 1.2 PS',
       'Hyundai Santro Xing XS', 'Maruti Suzuki Ciaz VXi Plus',
       'Maruti Suzuki Zen VX', 'Hyundai Creta 1.6 SX Plus Petrol',
       'Tata indigo ecs LX, 201', 'Mahindra Scorpio SLX',
       'Toyota Innova 2.5 G BS III 8 STR',
       'Maruti Suzuki Wagon R LXI BS IV', 'Tata Nano Cx BSIV',
       'Maruti Suzuki Alto Std BS IV', 'Maruti Suzuki Wagon R LXi BS III',
       'Maruti Suzuki Swift VXI BSIII',
       'Tata Sumo Victa EX 10 by 7 Str BSIII', 'MARUTI SUZUKI DESI',
       'Volkswagen Passat Diesel Comfortline AT',
       'Renault Scala RxL Diesel Travelogue',
       'Hyundai Grand i10 Sportz O 1.2 Kappa VTVT',
       'Hyundai i20 Active 1.2 SX', 'Mahindra Xylo E4',
       'Mahindra Jeep MM 550 XDB', 'Mahindra Bolero SLE BS IV',
       'Force Motors Force One LX ABS 7 STR', 'Maruti Suzuki SX4',
       'Toyota Etios', 'Honda City ZX VTEC',
       'Maruti Suzuki Wagon R LX BS III', 'Honda City VX O MT Diesel',
       'Mahindra Thar CRDe 4x4 AC',
       'Audi A4 1.8 TFSI Multitronic Premium Plus',
       'Mercedes Benz GLA Class 200 CDI Sport',
       'Land Rover Freelander 2 SE', 'Renault Kwid RXT',
       'Tata Aria Pleasure 4X2', 'Mercedes Benz B Class B180 Sports',
       'Datsun GO T O', 'Honda Jazz VX MT',
       'Hyundai i20 Active 1.4L SX O', 'Mini Cooper S',
       'Maruti Suzuki Ciaz ZXI Plus', 'Chevrolet Tavera Neo',
       'Hyundai Eon Sportz', 'Tata Sumo Gold Select Variant',
       'Maruti Suzuki Wagon R 1.0', 'Maruti Suzuki Esteem VXi BS III',
       'Chevrolet Enjoy 1.4 LS 8 STR', 'Maruti Suzuki Wagon R 1.0 VXi',
       'Nissan Terrano XL D Plus', 'Renault Duster 85 PS RxL Diesel',
       'Maruti Suzuki Dzire ZXI', 'Renault Kwid RXT Opt',
       'Maruti Suzuki Maruti 800 Std', 'Renault Kwid 1.0 RXT AMT',
       'Renault Scala RxL Diesel',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT O',
       'Chevrolet Beat LS Petrol', 'Hyundai Accent GLX', 'Yama',
       'Maruti Suzuki Swift LDi', 'Mahindra TUV300 T4 Plus',
       'Tata Indica V2 Xeta e GLE', 'Tata Indigo CS LS DiCOR',
       'Mahindra Scorpio VLX Special Edition BS III',
       'Tata Indica eV2 LS', 'Honda Accord',
       'Ford EcoSport Titanium 1.5 TDCi', 'Maruti Suzuki Ertiga',
       'Mahindra Scorpio 2.6 CRDe', 'Honda Mobilio',
       'Toyota Corolla Altis', 'Skoda Laura', 'Hyundai Verna Fluidic',
       'Maruti Suzuki Vitara Brezza', 'Tata Manza Aura Quadrajet',
       'Chevrolet Sail UVA Petrol LT ABS',
       'Hyundai Verna Fluidic 1.6 VTVT SX',
       'Audi A4 2.0 TDI 177bhp Premium', 'Hyundai Elantra SX',
       'Mahindra Scorpio VLX 4WD Airbag', 'Mahindra KUV100 K8 D 6 STR',
       'Hyundai Grand i10', 'Hyundai i10', 'Hyundai i20 Active',
       'Datsun Redi GO', 'Toyota Etios Liva', 'Hyundai Accent',
       'Hyundai Verna', 'Toyota Fortuner', 'Hyundai i10 Sportz',
       'Mahindra Bolero Power Plus SLE', 'selling car Ta',
       'Honda City 1.5 V MT Exclusive', 'Chevrolet Spark LT 1.0 Airbag',
       'Tata Indigo eCS VX CR4 BS IV', 'Tata Zest 90',
       'Skoda Rapid Elegance 1.6 TDI CR MT', 'Tata Vista Quadrajet VX',
       'Maruti Suzuki Alto K10 VXi AT', 'Maruti Suzuki Zen LXi BS III',
       'Maruti Suzuki Swift Dzire Tour LDi', 'Honda City ZX EXi',
       'Chevrolet Beat Diesel', 'Maruti Suzuki Swift Dzire car',
       'Hyundai Verna 1.4 VTVT', 'Toyota Innova 2.5 E MS 7 STR BS IV',
       'Maruti Suzuki Maruti 800 Std – Befo',
       'Hyundai Elite i20 Asta 1.4 CRDI',
       'Maruti Suzuki Swift Dzire Tour (Gat',
       'Maruti Suzuki Versa DX2 8 SEATER BSIII',
       'Tata Indigo LX TDI BS III',
       'Volkswagen Vento Konekt Diesel Highline',
       'Mercedes Benz C Class 200 CDI Classic', 'URJE',
       'Hyundai Santro Xing GLS', 'Maruti Suzuki Omni Limited Edition',
       'Hyundai Sonata Transform 2.4 GDi MT',
       'Hyundai Elite i20 Sportz 1.2', 'Honda Jazz S MT',
       'Hyundai Grand i10 Sportz 1.2 Kappa VTVT',
       'Maruti Suzuki Zen LXi BSII',
       'Mahindra Scorpio W Turbo 2.6DX 9 Seater',
       'Swift Dzire Tour 27 Dec 2016 Regis', 'Maruti Suzuki Alto K10 VXi',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT', 'Mahindra XUV500 W8',
       'Hyundai i20 Magna O 1.2', 'Renault Duster 85 PS RxL Explore LE',
       'Honda Brio V MT', 'Mahindra TUV300 T8',
       'Nissan X Trail Select Variant', 'Ford Ikon 1.3 CLXi NXt Finesse',
       'Toyota Fortuner 3.0 4x4 MT', 'Tata Manza ELAN Quadrajet',
       'Tata zest x', 'Mahindra xyl',
       'Mercedes Benz A Class A 180 Sport Petrol', 'Tata Indigo LS',
       'Hyundai i20 Magna 1.2', 'Used Commercial Maruti Omn',
       'Honda Amaze 1.5 E i DTEC', 'Hyundai Verna 1.6 EX VTVT',
       'BMW 5 Series 520d Sedan', 'Skoda Superb 1.8 TFSI AT',
       'Audi Q3 2.0 TDI quattro Premium', 'Mahindra Bolero DI BSII',
       'Maruti Suzuki Zen Estilo LXI Green CNG',
       'Ford Figo Duratorq Diesel Titanium 1.4',
       'Maruti Suzuki Wagon R VXI BS IV', 'Mahindra Logan Diesel 1.5 DLS',
       'Tata Nano GenX XMA', 'Honda City SV', 'Ford Figo Petrol LXI',
       'Hyundai i10 Magna 1.2 Kappa2', 'Toyota Corolla H2',
       'Maruti Suzuki Swift Dzire Tour VXi', 'Tata Indigo CS eLS BS IV',
       'Hyundai Xcent Base 1.1 CRDi', 'Hyundai Accent Executive Edition',
       'Tata Zest XE 75 PS Diesel', 'Maruti Suzuki Dzire LDI',
       'Tata Sumo Gold LX BS IV', 'Toyota Corolla Altis GL Petrol',
       'Maruti Suzuki Eeco 7 STR', 'Toyota Fortuner 3.0 4x2 MT',
       'Mahindra XUV500 W6', 'Tata Tigor Revotron XZ',
       'Maruti Suzuki 800', 'Honda Mobilio S i DTEC',
       'Hyundai Verna 1.6 CRDI E', 'Maruti Suzuki Omni Select Variant',
       'Tata Indica', 'Hyundai Santro Xing', 'Maruti Suzuki Zen Estilo',
       'Honda Brio VX AT', 'Maruti Suzuki Wagon R Select Variant',
       'Tata Nano Lx BSIV', 'Jaguar XE XE Portfolio',
       'Hyundai Xcent S 1.2', 'Hyundai Eon Magna Plus',
       'Maruti Suzuki Ritz GENUS VXI',
       'Hyundai Grand i10 Magna AT 1.2 Kappa VTVT',
       'Hyundai Eon D Lite Plus', 'Honda Amaze 1.2 VX i VTEC',
       'Maruti Suzuki Estilo VXi ABS BS IV',
       'Maruti Suzuki Vitara Brezza LDi O', 'Toyota Innova 2.0 V',
       'Hyundai Creta 1.6 SX Plus Petrol AT', 'Mahindra Scorpio Vlx BSIV',
       'Mitsubishi Lancer 1.8 LXi', 'Maruti Suzuki Maruti 800 AC',
       'Maruti Suzuki Alto 800 LXI CNG O', 'Ford Fiesta SXi 1.6 ABS',
       'Maruti Suzuki Ritz VDi', 'Maruti Suzuki Estilo LX BS IV',
       'Audi A6 2.0 TDI Premium', 'Maruti Suzuki Alto',
       'Maruti Suzuki Baleno Sigma 1.2', 'Hyundai Verna 1.6 SX VTVT AT',
       'Maruti Suzuki Swift GLAM', 'Hyundai Getz Prime 1.3 GVS',
       'Hyundai Santro', 'Hyundai Getz Prime 1.3 GLX',
       'Chevrolet Beat PS Diesel', 'Ford EcoSport Trend 1.5 Ti VCT',
       'Tata Indica V2 DLG', 'BMW X1 xDrive20d xLine',
       'Honda City 1.5 V AT', 'Tata Nano', 'Chevrolet Cruze LTZ AT',
       'Hyun', 'Maruti Suzuki Swift Dzire VDi', 'Mahindra XUV500 W10',
       'Maruti Suzuki Alto K10 LXi CNG', 'Hyundai Accent GLE',
       'Force Motors One SUV', 'Datsun Go Plus T O',
       'Chevrolet Spark 1.0 LT', 'Toyota Etios Liva GD',
       'Renault Duster 85PS Diesel RxL Optional with Nav',
       'Chevrolet Enjoy', 'BMW 5 Series 530i', 'Chevrolet Cruze LTZ',
       'Jeep Wrangler Unlimited 4x4 Diesel',
       'Hyundai Verna VGT CRDi SX ABS', 'Maruti Suzuki Omni',
       'Maruti Suzuki Celerio VDi', 'Tata Zest Quadrajet 1.3',
       'Tata Indigo CS eLX BS IV', 'Hyundai i10 Era',
       'Tata Indigo eCS LX CR4 BS IV', 'Tata Indigo Marina LS',
       'Commercial Chevrolet Sail Hatchback ca', 'Hyundai Xcent SX 1.2',
       'Tata Nano LX Special Edition', 'Commercial Car Ta',
       'Renault Duster 110 PS RxZ Diesel',
       'Maruti Suzuki Wagon R AX BSIV', 'Maruti Suzuki Alto K10 New',
       'tata Indica', 'Mahindra Xylo E8', 'Tata Manza Aqua Quadrajet',
       'Used bt new conditions ta', 'Renault Kwid 1.0', 'Sale tata',
       'Tata Venture EX 8 STR', 'Maruti Suzuki Swift Dzire Tour LXi',
       'Maruti Suzuki Alto LX BSII', 'Skoda Octavia Classic 1.9 TDI MT',
       'Maruti Suzuki Omni LPG BS IV', 'Tata Sumo Gold EX BS IV',
       'Tata indigo 2017 top model..', 'Hyundai Verna 1.6 CRDI SX',
       'Mahindra Scorpio SLX 2.6 Turbo 8 Str', 'Ford Ikon 1.6 Nxt',
       'Tata indigo', 'Toyota Innova 2.5 V 7 STR', 'Nissan Sunny XL',
       'Maruti Suzuki Swift VDi BS IV',
       'very good condition tata bolts are av', 'Toyota Innova 2.0 G4',
       'Sale Hyundai xcent commerc', 'Maruti Suzuki Swift VDi ABS',
       'Hyundai Elite i20 Asta 1.2', 'Volkswagen Polo Trendline 1.5L D',
       'Toyota Etios Liva Diesel', 'Maruti Suzuki Ciaz ZXi Plus RS',
       'Hyundai Elantra 1.8 S', 'Ford EcoSport Trend 1.5L Ti VCT',
       'Jaguar XF 2.2 Diesel Luxury',
       'Audi Q5 2.0 TDI quattro Premium Plus', 'BMW 3 Series 320d Sedan',
       'Maruti Suzuki Swift ZXi 1.2 BS IV', 'BMW X1 sDrive20d',
       'Maruti Suzuki S Cross Sigma 1.3', 'Maruti Suzuki Ertiga LDi',
       'Volkswagen Vento Comfortline Petrol', 'Mahindra KUV100',
       'Maruti Suzuki Swift Dzire Tour VDi', 'Mahindra Scorpio 2.6 SLX',
       'Maruti Suzuki Omni 8 STR BS III',
       'Volkswagen Jetta Comfortline 1.9 TDI AT', 'Volvo S80 Summum D4',
       'Toyota Corolla Altis VL AT Petrol',
       'Mitsubishi Pajero Sport 2.5 AT', 'Chevrolet Beat LT Petrol',
       'BMW X1', 'Mercedes Benz C Class C 220 CDI Avantgarde',
       'Volkswagen Vento Comfortline Diesel', 'Tata Indigo CS GLS',
       'Ford Figo Petrol Titanium', 'Honda City ZX GXi',
       'Maruti Suzuki Wagon R Duo Lxi', 'Maruti Suzuki Zen LX BSII',
       'Renault Duster RxL Petrol', 'Maruti Suzuki Baleno Zeta 1.2',
       'Honda WR V S MT Petrol', 'Renault Duster 110 PS RxL Diesel',
       'Mahindra Scorpio LX BS III',
       'Maruti Suzuki SX4 Celebration Diesel',
       'Audi A3 Cabriolet 40 TFSI',
       'I want to sell my commercial car due t',
       'Hyundai Santro AE GLS Audio',
       'i want sale my car.no emi....uber atta', 'Tata ZEST 6 month old',
       'Mahindra Xylo D2 BS IV', 'Hyundai Getz GLE',
       'Hyundai Creta 1.6 SX', 'Hyundai Santro Xing XL AT eRLX Euro III',
       'Hyundai Santro Xing XL eRLX Euro III',
       'Tata Indica V2 DLS BS III', 'Honda City 1.5 E MT',
       'Nissan Micra XL', 'Honda City 1.5 S Inspire',
       'Tata Indica eV2 eXeta eGLX', 'Maruti Suzuki Omni E 8 STR BS IV',
       'MARUTI SUZUKI ERTIGA F', 'Hyundai Verna 1.6 CRDI SX Plus AT',
       'Chevrolet Tavera LS B3 10 Seats BSII', 'Tata Tiago Revotron XM',
       'Tata Tiago Revotorq XZ', 'Tata Nexon', 'Tata',
       'Hindustan Motors Ambassador Classic Mark 4 – Befo',
       'Ford Fusion 1.4 TDCi Diesel',
       'Fiat Linea Emotion 1.4 L T Jet Petrol',
       'Ford Ikon 1.3 Flair Josh 100', 'Tata Indica V2 LS',
       'Mahindra Xylo D2', 'Hyundai Eon Magna',
       'Tata Sumo Grande MKII GX', 'Volkswagen Polo Highline1.2L P',
       'Tata Tiago Revotron XZ', 'Tata Indigo eCS',
       '2012 Tata Sumo Gold f', 'Mahindra Xylo E8 BS IV',
       'Well mentained Tata Sumo',
       'all paper updated tata indica v2 and u',
       'Maruti Ertiga showroom condition with',
       '7 SEATER MAHINDRA BOLERO IN VERY GOOD', '9 SEATER MAHINDRA BOL',
       'scratch less Tata I', 'Maruti Suzuki swift dzire for sale in',
       'Commercial Chevrolet beat for sale in',
       'urgent sell my Mahindra qu', 'Tata Sumo Gold FX BSIII',
       'sell my car Maruti Suzuki Swif',
       'Maruti Suzuki Swift Dzire good car fo', 'Hyunda',
       'Commercial Maruti Suzuki Alto Lxi 800', 'urgent sale Ta',
       'Maruti Suzuki Alto vxi t', 'tata', 'TATA INDI', 'Hyundai Creta',
       'Tata Bolt XM Petrol', 'Hyundai Venue', 'Maruti Suzuki Ritz',
       'Renault Lodgy', 'Hyundai i20 Asta',
       'Maruti Suzuki Swift Select Variant', 'Tata Indica V2 DLX BS III',
       'Mahindra Scorpio VLX 2.2 mHawk Airbag BSIV',
       'Toyota Innova 2.5 E 8 STR', 'Mahindra KUV100 K8 6 STR',
       'Datsun Go Plus', 'Ford Endeavor 4x4 Thunder Plus',
       'Tata Indica V2', 'Hyundai Santro Xing GL',
       'Toyota Innova 2.5 Z Diesel 7 Seater',
       'Any type car avaiabel hare...comercica', 'Maruti Suzuki Alto AX',
       'Mahindra Logan', 'Maruti Suzuki 800 Std BS III',
       'Chevrolet Sail 1.2 LS',
       'Volkswagen Vento Highline Plus 1.5 Diesel', 'Tata Manza',
       'Toyota Innova 2.0 G1 Petrol 8seater', 'Toyota Etios G',
       'Toyota Qualis', 'Mahindra Quanto C4', 'Maruti Suzuki Swift Dzire',
       'Hyundai i20 Select Variant', 'Honda City VX Petrol',
       'Hyundai Getz', 'Mercedes Benz C Class 200 K MT', 'Skoda Fabia',
       'Maruti Suzuki Alto 800 Select Variant',
       'Maruti Suzuki Ritz VXI ABS', 'tata zest 2017 f',
       'Tata Indica V2 DLE BS III', 'Ta', 'Tata Zest XM Diesel',
       'Honda Amaze 1.2 E i VTEC', 'Chevrolet Sail 1.2 LT ABS'],
      dtype=object)

In [404]:
backup = car.copy()

In [405]:
car['year']

0      2007
1      2006
2      2018
3      2014
4      2014
       ...
887    zest
888    2018
889    2013
890    2014
891    2014
Name: year, Length: 892, dtype: object

In [406]:
car=car[car['year'].str.isnumeric()]

In [407]:
car['year'] = car['year'].astype(int)

In [408]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int32
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int32(1), object(5)
memory usage: 42.8+ KB

In [409]:
car['Price']

0             80,000
1           4,25,000
2      Ask For Price
3           3,25,000
4           5,75,000
           ...
886         3,00,000
888         2,60,000
889         3,90,000
890         1,80,000
891         1,60,000
Name: Price, Length: 842, dtype: object

In [410]:
car=car[car['Price'] != "Ask For Price"]

In [411]:
car["Price"] = car["Price"].str.replace(",","").astype(int) # removed comma and converted to obj to int

In [412]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int32
 3   Price       819 non-null    int32
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.4+ KB

In [413]:
car['kms_driven']

0        45,000 kms
1            40 kms
3        28,000 kms
4        36,000 kms
6        41,000 kms
           ...
886    1,32,000 kms
888      27,000 kms
889      40,000 kms
890          Petrol
891          Petrol
Name: kms_driven, Length: 819, dtype: object

In [414]:
car['kms_driven'].str.split(" ").str.get(0)

0        45,000
1            40
3        28,000
4        36,000
6        41,000
         ...
886    1,32,000
888      27,000
889      40,000
890      Petrol
891      Petrol
Name: kms_driven, Length: 819, dtype: object

In [415]:
car['kms_driven'].str.split(" ").str.get(0).str.replace(",","")

0       45000
1          40
3       28000
4       36000
6       41000
        ...
886    132000
888     27000
889     40000
890    Petrol
891    Petrol
Name: kms_driven, Length: 819, dtype: object

In [416]:
car['kms_driven']=car['kms_driven'].str.split(" ").str.get(0).str.replace(",","")

In [417]:
car = car[car['kms_driven'].str.isnumeric()]  # keeping only numeric value removing nan and petrol value

In [418]:
car['kms_driven'] = car['kms_driven'].astype(int)

In [419]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32
 3   Price       817 non-null    int32
 4   kms_driven  817 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.1+ KB

In [420]:
car[car['fuel_type'].isna()]

               name company  year   Price  kms_driven fuel_type
132  Toyota Corolla  Toyota  2009  275000       26000       NaN

In [421]:
car = car[~car['fuel_type'].isna()]

In [422]:
car['name']

0        Hyundai Santro Xing XO eRLX Euro III
1                     Mahindra Jeep CL550 MDI
3      Hyundai Grand i10 Magna 1.2 Kappa VTVT
4            Ford EcoSport Titanium 1.5L TDCi
6                                   Ford Figo
                        ...
883                Maruti Suzuki Ritz VXI ABS
885                 Tata Indica V2 DLE BS III
886                      Toyota Corolla Altis
888                       Tata Zest XM Diesel
889                        Mahindra Quanto C8
Name: name, Length: 816, dtype: object

In [423]:
car['name'].str.split(' ').str.slice(0,3).str.join(' ') # keeping only first 3 words

0         Hyundai Santro Xing
1         Mahindra Jeep CL550
3           Hyundai Grand i10
4      Ford EcoSport Titanium
6                   Ford Figo
                ...
883        Maruti Suzuki Ritz
885            Tata Indica V2
886      Toyota Corolla Altis
888              Tata Zest XM
889        Mahindra Quanto C8
Name: name, Length: 816, dtype: object

In [424]:
car['name'].str.split(' ').str.slice(0,3).str.join(' ')

0         Hyundai Santro Xing
1         Mahindra Jeep CL550
3           Hyundai Grand i10
4      Ford EcoSport Titanium
6                   Ford Figo
                ...
883        Maruti Suzuki Ritz
885            Tata Indica V2
886      Toyota Corolla Altis
888              Tata Zest XM
889        Mahindra Quanto C8
Name: name, Length: 816, dtype: object

In [425]:
car['name'] = car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [426]:
car # index are not in sequence

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [427]:
car.reset_index(drop=True)

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [428]:
car = car.reset_index(drop=True)

In [429]:
car.head(50)

                       name     company  year    Price  kms_driven fuel_type
0       Hyundai Santro Xing     Hyundai  2007    80000       45000    Petrol
1       Mahindra Jeep CL550    Mahindra  2006   425000          40    Diesel
2         Hyundai Grand i10     Hyundai  2014   325000       28000    Petrol
3    Ford EcoSport Titanium        Ford  2014   575000       36000    Diesel
4                 Ford Figo        Ford  2012   175000       41000    Diesel
5               Hyundai Eon     Hyundai  2013   190000       25000    Petrol
6    Ford EcoSport Ambiente        Ford  2016   830000       24530    Diesel
7        Maruti Suzuki Alto      Maruti  2015   250000       60000    Petrol
8       Skoda Fabia Classic       Skoda  2010   182000       60000    Petrol
9    Maruti Suzuki Stingray      Maruti  2015   315000       30000    Petrol
10        Hyundai Elite i20     Hyundai  2014   415000       32000    Petrol
11     Mahindra Scorpio SLE    Mahindra  2015   320000       48660    Diesel
12      Hyundai Santro Xing     Hyundai  2007    80000       45000    Petrol
13      Mahindra Jeep CL550    Mahindra  2006   425000          40    Diesel
14                  Audi A8        Audi  2017  1000000        4000    Petrol
15                  Audi Q7        Audi  2014   500000       16934    Diesel
16     Mahindra Scorpio S10    Mahindra  2016   350000       43000    Diesel
17       Maruti Suzuki Alto      Maruti  2014   160000       35550    Petrol
18     Mahindra Scorpio S10    Mahindra  2016   350000       43000    Diesel
19     Mahindra Scorpio S10    Mahindra  2016   310000       39522    Diesel
20       Maruti Suzuki Alto      Maruti  2015    75000       39000    Petrol
21       Hyundai i20 Sportz     Hyundai  2012   100000       55000    Petrol
22       Hyundai i20 Sportz     Hyundai  2012   100000       55000    Petrol
23       Hyundai i20 Sportz     Hyundai  2012   100000       55000    Petrol
24       Maruti Suzuki Alto      Maruti  2017   190000       72000    Petrol
25     Maruti Suzuki Vitara      Maruti  2016   290000       15975    Diesel
26       Maruti Suzuki Alto      Maruti  2008    95000       70000    Petrol
27       Mahindra Bolero DI    Mahindra  2017   180000       23452    Diesel
28      Maruti Suzuki Swift      Maruti  2014   385000       35522    Diesel
29     Mahindra Scorpio S10    Mahindra  2015   250000       48508    Diesel
30      Maruti Suzuki Swift      Maruti  2017   180000       15487    Petrol
31      Maruti Suzuki Wagon      Maruti  2013   105000       39000    Petrol
32      Maruti Suzuki Wagon      Maruti  2013   105000       39000    Petrol
33        Toyota Innova 2.0      Toyota  2012   650000       82000    Diesel
34         Renault Lodgy 85     Renault  2018   689999       20000    Diesel
35      Skoda Yeti Ambition       Skoda  2012   448000       68000    Diesel
36     Maruti Suzuki Baleno      Maruti  2017   549000       32000    Diesel
37       Renault Duster 110     Renault  2012   501000       38000    Diesel
38        Renault Duster 85     Renault  2013   489999       27000    Diesel
39           Honda City 1.5       Honda  2011   280000       33000    Petrol
40       Maruti Suzuki Alto      Maruti  2015   250000       60000    Petrol
41      Maruti Suzuki Dzire      Maruti  2013   349999       46000    Diesel
42              Honda Amaze       Honda  2013   284999       46000    Diesel
43          Honda Amaze 1.5       Honda  2015   345000       36000    Diesel
44               Honda City       Honda  2015   499999       55000    Petrol
45           Datsun Redi GO      Datsun  2017   235000       16000    Petrol
46        Maruti Suzuki SX4      Maruti  2010   249999       36000    Petrol
47  Mitsubishi Pajero Sport  Mitsubishi  2015  1475000       47000    Diesel
48       Mahindra Bolero DI    Mahindra  2017   180000       23452    Diesel
49      Maruti Suzuki Swift      Maruti  2014   385000       35522    Diesel

In [430]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int32
 3   Price       816 non-null    int32
 4   kms_driven  816 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 28.8+ KB

In [431]:
car.describe(include='all')

,name,company,year,Price,kms_driven,fuel_type
count,816,816,816.000000,8.160000e+02,816.000000,816
unique,254,25,NaN,NaN,NaN,3
top,Maruti Suzuki Swift,Maruti,NaN,NaN,NaN,Petrol
freq,51,221,NaN,NaN,NaN,428
mean,NaN,NaN,2012.444853,4.117176e+05,46275.531863,NaN
std,NaN,NaN,4.002992,4.751844e+05,34297.428044,NaN
min,NaN,NaN,1995.000000,3.000000e+04,0.000000,NaN
25%,NaN,NaN,2010.000000,1.750000e+05,27000.000000,NaN
50%,NaN,NaN,2013.000000,2.999990e+05,41000.000000,NaN
75%,NaN,NaN,2015.000000,4.912500e+05,56818.500000,NaN
max,NaN,NaN,2019.000000,8.500003e+06,400000.000000,NaN

In [432]:
car.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [433]:
car[car['Price'] > 6e6]  # outlier car price is greater than 60,00000

                   name   company  year    Price  kms_driven fuel_type
534  Mahindra XUV500 W6  Mahindra  2014  8500003       45000    Diesel

In [434]:
car[car['Price'] < 6e6].reset_index(drop=True)

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [435]:
car = car[car['Price'] < 6e6].reset_index(drop=True)

In [436]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

# Cleaned Data stored in a file

In [437]:
car.to_csv('Cleaned Car.csv')

In [439]:
y = car['Price']

In [ ]:
X = car.drop(columns=['Price'])

In [440]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y, test_size=0.2)

In [441]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [443]:
ohe = OneHotEncoder()
ohe.fit(X[['name','company','fuel_type']])

OneHotEncoder()

In [450]:
ohe.categories_

[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
        'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
        'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
        'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
        'Chevrolet Beat LS', 'Chevrolet Beat LT', 'Chevrolet Beat PS',
        'Chevrolet Cruze LTZ', 'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4',
        'Chevrolet Sail 1.2', 'Chevrolet Sail UVA', 'Chevrolet Spark',
        'Chevrolet Spark 1.0', 'Chevrolet Spark LS', 'Chevrolet Spark LT',
        'Chevrolet Tavera LS', 'Chevrolet Tavera Neo', 'Datsun GO T',
        'Datsun Go Plus', 'Datsun Redi GO', 'Fiat Linea Emotion',
        'Fiat Petra ELX', 'Fiat Punto Emotion', 'Force Motors Force',
        'Force Motors One', 'Ford EcoSport', 'Ford EcoSport Ambiente',
        'Ford EcoSport Titanium', 'Ford EcoSport Trend',
        'Ford Endeavor 4x4', 'Ford Fiesta', 'Ford Fiesta SXi', 'Ford Figo',
        'Ford Figo Diesel', 'Ford Figo Duratorq', 'Ford Figo Petrol',
        'Ford Fusion 1.4', 'Ford Ikon 1.3', 'Ford Ikon 1.6',
        'Hindustan Motors Ambassador', 'Honda Accord', 'Honda Amaze',
        'Honda Amaze 1.2', 'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V',
        'Honda Brio VX', 'Honda City', 'Honda City 1.5', 'Honda City SV',
        'Honda City VX', 'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX',
        'Honda Mobilio', 'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
        'Hyundai Accent Executive', 'Hyundai Accent GLE',
        'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
        'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
        'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
        'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
        'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
        'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
        'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
        'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
        'Hyundai Verna Transform', 'Hyundai Verna VGT',
        'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
        'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
        'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
        'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
        'Jaguar XE XE', 'Jaguar XF 2.2', 'Jeep Wrangler Unlimited',
        'Land Rover Freelander', 'Mahindra Bolero DI',
        'Mahindra Bolero Power', 'Mahindra Bolero SLE',
        'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
        'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
        'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
        'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
        'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
        'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
        'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
        'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra TUV300 T8',
        'Mahindra Thar CRDe', 'Mahindra XUV500', 'Mahindra XUV500 W10',
        'Mahindra XUV500 W6', 'Mahindra XUV500 W8', 'Mahindra Xylo D2',
        'Mahindra Xylo E4', 'Mahindra Xylo E8', 'Maruti Suzuki 800',
        'Maruti Suzuki A', 'Maruti Suzuki Alto', 'Maruti Suzuki Baleno',
        'Maruti Suzuki Celerio', 'Maruti Suzuki Ciaz',
        'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
        'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
        'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
        'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
        'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
        'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
        'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
        'Mercedes Benz A', 'Mercedes Benz B', 'Mercedes Benz C',
        'Mercedes Benz GLA', 'Mini Cooper S', 'Mitsubishi Lancer 1.8',
        'Mitsubishi Pajero Sport', 'Nissan Micra XL', 'Nissan Micra XV',
        'Nissan Sunny', 'Nissan Sunny XL', 'Nissan Terrano XL',
        'Nissan X Trail', 'Renault Duster', 'Renault Duster 110',
        'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
        'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
        'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
        'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
        'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
        'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
        'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
        'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
        'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
        'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
        'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
        'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
        'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
        'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
        'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
        'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
        'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
        'Toyota Etios Liva', 'Toyota Fortuner', 'Toyota Fortuner 3.0',
        'Toyota Innova 2.0', 'Toyota Innova 2.5', 'Toyota Qualis',
        'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
        'Volkswagen Passat Diesel', 'Volkswagen Polo',
        'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
        'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
        'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
        'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [453]:
column_trans = make_column_transformer((OneHotEncoder(categories = ohe.categories_),['name','company','fuel_type']),remainder='passthrough')

In [ ]:
# column_trans = make_column_transformer((OneHotEncoder(),['name','company','fuel_type']),
# (SimpleImputer),  we can use simple imputer to remove nan values
# remainder='passthrough')

In [454]:
lr = LinearRegression()

In [455]:
pipe = make_pipeline(column_trans,lr)

In [456]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [458]:
y_pred = pipe.predict(X_test)
y_pred

array([ 440085.27828076,  315394.69570886, 1801267.63294718,
        162339.19025753,  533138.74798732,   90578.95428056,
        592582.61852695,  527932.9747435 ,  392668.95638364,
        -75550.56365076,  297583.00558504,  117297.57715221,
        544521.61582237,  432620.94944625,  340503.60876281,
        159255.31716004,  202545.06876033,  600840.2130904 ,
        493561.36400149,  186917.41494047,   71838.49178924,
        173522.1295763 , 2234974.47499238,  570951.67766403,
       -195489.72811771,  374170.8212589 , 1075236.84229117,
        221237.46296583,  579624.15013164,  393623.13289203,
        225181.87649133,  424263.10800438,  233266.97812688,
        420115.84164445,  192595.62647694,  289648.07527453,
        304400.91506166,  723827.19892549,  260298.93795097,
        397295.09914501,  627820.63891038,  370607.00674217,
        576166.5223534 ,  695626.45548532,  198699.25688982,
        268708.21405084, 1407489.73425427,  236143.44174968,
        454840.36024859,  551233.21373127,  467864.43256719,
        275118.43108831,  238933.1871194 ,  397126.50708114,
        627820.63891038,  196748.64984491,  462925.01126464,
         39237.03527402, 1054119.94537839,  322589.8578143 ,
        334389.87227472,  460144.79929541,  491690.85114691,
        342785.56099217,  475209.83690138,  419739.37318864,
        240030.4527763 ,  252195.54676326,  378172.52330076,
        569138.33428802,  183890.87065133,  378535.70977667,
        396964.60566217,  472738.03868736,  333557.73827327,
        283417.54556801,  658859.89614235, -168448.68970345,
         43301.49389519,  454038.76017451,  348174.35342695,
        381128.66339194,  315335.07165251,  559261.80688319,
        553604.15149643,  461214.00600135,  901133.86194769,
       1049473.44127145,  587673.42707967,  169510.81119954,
        454840.36024859,  656890.13117874,  178805.20264833,
        530047.03301968,  341552.12776161,  389577.24141601,
        527985.88970792,  513500.25075171, 1674073.09383424,
        334389.87227472,   91094.2401085 ,  516694.08961979,
        288867.81151439,  430721.85103817,  268810.46613451,
        425244.18036769,  519961.91207352,  408973.4118006 ,
        599525.00112227,  283313.77348071,  432482.70151498,
        152906.96464973,  408282.78825077,  297583.00558504,
       1601697.36618014,  280927.07343739,  378172.52330076,
        352777.36035463,  466104.82295355,  309830.11389798,
        565387.6036061 ,  590182.54763196,  138059.04860505,
        133567.12015098,  656278.27202804,  505365.83827282,
        402725.54049612,   93556.35673946,  918509.08457249,
        102757.97831451,  590138.26905508,  447985.95102464,
        449454.61722052,  499163.83007985,  148269.39219828,
        516956.86982741,  311941.75084165,  364558.70574766,
        460110.87936872,  201551.47149949,  264297.42870159,
        270996.1444648 ,  119362.16474835,  401874.65358856,
        118600.1746454 ,  480596.95260856,  591204.50178301,
       -194049.64417212,  596707.5167952 ,  261596.46454336,
        764595.74980144, 2234974.47499238,  475191.99944299,
        284236.96560264,  313797.30964226,  641864.63533496,
        199933.77286895,  208911.36861356, 1041744.15385236,
        221224.88963409,  395199.80289524,  159332.67547747,
        264298.46248144])

In [459]:
r2_score(y_test , y_pred)

0.6736888965897481

In [464]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=i)
    lr = LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    print(r2_score(y_test,y_pred),i)
    scores.append(r2_score(y_test,y_pred))

0.6589775490516477 0
0.47859534625114053 1
0.6206184325887315 2
0.5370851059720391 3
0.8189003209843422 4
0.6634592678218548 5
0.627651080774843 6
0.6298500612485975 7
0.6721337147755825 8
0.569999290976279 9
0.648410356051369 10
0.6085830042105451 11
0.4570387283628752 12
0.6674701982444136 13
0.5667086409016293 14
0.710110955902248 15
0.48789129723115376 16
0.6657624958397428 17
0.6089284148932655 18
0.6397685755956675 19
0.6410709224098974 20
0.6210283939684125 21
0.7366931810218385 22
0.6403435054918312 23
0.5492294440786976 24
0.49865430736412675 25
0.6732835680238167 26
0.7035631613026931 27
0.7254576384148604 28
0.6010349558544669 29
0.6245053608697559 30
0.6290270877645332 31
0.7651654313017575 32
0.7853874888796626 33
0.5622385517206983 34
0.685024845194027 35
0.5779619998835577 36
0.6170146213581826 37
0.5393853480656206 38
0.7164312140567131 39
0.32666867715670367 40
0.6733782138107586 41
0.5731311949541246 42
0.6659932444752472 43
0.6604128224175608 44
0.6975409772585117 45
0.5258705780715188 46
0.5882064290521126 47
0.7540188120977028 48
0.6861734869122942 49
0.5038058588989355 50
0.5964725808936133 51
0.6325679093210963 52
0.6638066957559459 53
0.5797623627769186 54
0.6974693540090504 55
0.7171752768166924 56
0.7195081853284038 57
0.760859173432595 58
0.48428354013704156 59
0.5849349181102559 60
0.5244371253247728 61
0.4330340417620896 62
0.6189051514339482 63
0.607522089011671 64
0.6349243275736114 65
0.4810243158116734 66
0.6590615854542154 67
0.6214586085522245 68
0.743274946513606 69
0.6997074685617691 70
0.718579504415433 71
0.5796151530076887 72
0.7034350832805074 73
0.5518161471757719 74
0.5694855898282613 75
0.44927656745228084 76
0.6050835178219862 77
0.5738343223155049 78
0.6460411861883026 79
0.5886213603663246 80
0.5856527297265843 81
0.6765398800588244 82
0.744922939021712 83
0.6389826087094421 84
0.6358498527695688 85
0.6852016031039259 86
0.5373334373438552 87
0.6030204267549185 88
0.638377009894445 89
0.6809872042573941 90
0.5840677085925137 91
0.6883266712274796 92
0.4945068201935203 93
0.6331518312398363 94
0.6589982197584234 95
0.6383970274949671 96
0.685671676550484 97
0.6751357998207606 98
0.5924046045484042 99
0.6899601939018103 100
0.6600102221531261 101
0.683756615453387 102
0.6149163121355778 103
0.7041215445534494 104
0.5649578310778633 105
0.6078455341307166 106
0.5764028894036719 107
0.5851033777036474 108
0.7107005842382339 109
0.6766878812600473 110
0.659598128547024 111
0.5127821712678797 112
0.6956098077498688 113
0.712808743027473 114
0.5676531508773566 115
0.5902229692039391 116
0.6525735835868977 117
0.5256896650072882 118
0.7228177121081314 119
0.6581692762564109 120
0.5953147521353028 121
0.7076577689835495 122
0.6261015053194339 123
0.8216326112181462 124
0.681005019606276 125
0.637730870806759 126
0.6239460016246308 127
0.5864202001321324 128
0.550372528804032 129
0.6062859286221297 130
0.5323297110123215 131
0.6591277884511229 132
0.5821127184549941 133
0.7027029489715686 134
0.7148873283691211 135
0.5440179467037363 136
0.7128697273498124 137
0.6494389093638127 138
0.5590970714802499 139
0.7181361400409276 140
0.586705867369776 141
0.6612224480626586 142
0.7165643911721142 143
0.6245318632189201 144
0.5545537312096575 145
0.6359565804596823 146
0.588046184004918 147
0.5634737924621669 148
0.6069053339472597 149
0.6277211437794104 150
0.7724596338646768 151
0.565661196840624 152
0.5011852453586854 153
0.634135305666903 154
0.658846905817982 155
0.41606685035235824 156
0.7312052473847346 157
0.6297170749145033 158
0.6780739468150099 159
0.6478383058539585 160
0.581544526951242 161
0.6642600005835593 162
0.5706479505342106 163
0.54079496160464 164
0.6904361318757128 165
0.6572538443831808 166
0.48755369980445395 167
0.5687885149270496 168
0.6962773342371886 169
0.6922986141878773 170
0.6496643915200366 171
0.8164623049986885 172
0.718992939258467 173
0.5470821486753814 174
0.6143164502192797 175
0.7019970068120145 176
0.6112378221197254 177
0.7144213545366009 178
0.6795652793537643 179
0.6414515027744365 180
0.6170223210884662 181
0.6744829735207113 182
0.638957043691846 183
0.5049458053870068 184
0.6668450507209176 185
0.7358344497092881 186
0.687191073672583 187
0.6957933389418236 188
0.5728625851958813 189
0.7118277958664974 190
0.6646766794442025 191
0.579138851056737 192
0.6910788510484065 193
0.7292967069082062 194
0.6272207042044369 195
0.6315943191591371 196
0.7494009751972648 197
0.40231095224801017 198
0.7100659355621983 199
0.7154939229750867 200
0.45221334912847166 201
0.6115894971535283 202
0.7847693437331795 203
0.5828448545470719 204
0.7267676887729266 205
0.7711396213904578 206
0.5696036103014482 207
0.6767090630817606 208
0.3007879590164988 209
0.49257246733488314 210
0.5097936446676645 211
0.5691023806941338 212
0.6185929464484128 213
0.6759133226274681 214
0.6179569497577726 215
0.5303632563728018 216
0.6362584065335504 217
0.5417923705224519 218
0.5760916790679342 219
0.5905489510022623 220
0.6818009905460174 221
0.4754815031310341 222
0.49581214147159736 223
0.5517618814834195 224
0.7244657270988821 225
0.7406195756855021 226
0.6385679809470548 227
0.7309062731488489 228
0.5782879205308271 229
0.5551335353250881 230
0.5933498377668951 231
0.6307955710341127 232
0.4406629424695129 233
0.724503896010246 234
0.586696192238807 235
0.701015763803895 236
0.6090762393264832 237
0.5266450673911242 238
0.5940629263260737 239
0.5705695823833171 240
0.48454448375728754 241
0.5171441695827779 242
0.63995423553897 243
0.49584118736915606 244
0.7214297947765057 245
0.7796528629406407 246
0.7463062054569278 247
0.7799755460442197 248
0.543251051307208 249
0.6070998323214498 250
0.5083576250416957 251
0.5594153451493236 252
0.6510105640213559 253
0.5879417389945629 254
0.7699200009699592 255
0.559098383468555 256
0.6989268162691123 257
0.6601917740280057 258
0.5644983703485787 259
0.7154231110734142 260
0.7578394407335575 261
0.7048056324203738 262
0.7703171370590804 263
0.6347475984944395 264
0.5753635804860852 265
0.6586435895016174 266
0.6530084076580638 267
0.47476497716609756 268
0.5431659610279091 269
0.6272521191656313 270
0.5494026272230386 271
0.6220939317933835 272
0.617718455483529 273
0.715718886517769 274
0.628051483052195 275
0.7534293213562041 276
0.6969007525333072 277
0.6287015152260966 278
0.7884257210708662 279
0.6738637122231711 280
0.6544793734134398 281
0.6888912549388737 282
0.7344565980437592 283
0.717367605966728 284
0.5664224229554538 285
0.7224627867702149 286
0.5928211901636238 287
0.3849964409173614 288
0.45187066479110416 289
0.5199589141742247 290
0.6925845303182564 291
0.5407270156626004 292
0.7509819254014263 293
0.8132026476822222 294
0.6309730927488564 295
0.7431581573463812 296
0.7010412394197354 297
0.5330360736964104 298
0.6835420005115413 299
0.7690985544612867 300
0.7091754823868064 301
0.7634552773684578 302
0.48720695846269413 303
0.6521287709580831 304
0.5960583440913522 305
0.7878602283910798 306
0.6918057710083833 307
0.6490680688323722 308
0.696959823846441 309
0.6748556884234747 310
0.6069460756693468 311
0.5083068118708942 312
0.49942307520223916 313
0.5282074740228453 314
0.7374967421608402 315
0.5830901283409312 316
0.6074540941783003 317
0.653861252929492 318
0.5117568838602597 319
0.4756574646678432 320
0.5930869233062218 321
0.5330768783410326 322
0.5478043422123094 323
0.6196842257169537 324
0.5365585022571019 325
0.592806748124981 326
0.7232925949354405 327
0.6937351731472201 328
0.5143811342536755 329
0.653705150824555 330
0.502395819988567 331
0.6012789223908226 332
0.5731418740216581 333
0.6980506229895307 334
0.6015744725904919 335
0.5096215663914591 336
0.6708955908137405 337
0.6187269329740095 338
0.5840136031184426 339
0.7273559250139529 340
0.7318998894769165 341
0.5999653106643426 342
0.6714103418465805 343
0.6914680473314039 344
0.6448592637905641 345
0.6674358800100854 346
0.5895183291313577 347
0.705008413439635 348
0.6225986599643787 349
0.7436060829417994 350
0.7074400766978081 351
0.574243524784535 352
0.4603091115724156 353
0.728609034419164 354
0.6677603224863372 355
0.6984814672912064 356
0.6428797868061968 357
0.7076424292600532 358
0.5834397742434172 359
0.7067893925689152 360
0.6772115624397397 361
0.5385689925973852 362
0.695210784239148 363
0.7148432124497638 364
0.5628547160003579 365
0.6814875547156312 366
0.41687094645322753 367
0.7446908145713529 368
0.733920478799122 369
0.6802116225232707 370
0.6248997240398568 371
0.6434083336658589 372
0.6603125986727839 373
0.5147710764186529 374
0.5618444188026526 375
0.6845763439179546 376
0.5392514737249156 377
0.7351535461759946 378
0.770203406630189 379
0.6190280923459994 380
0.692908033812617 381
0.7054265531234298 382
0.8071026681861865 383
0.6887520674634988 384
0.7047053802578054 385
0.6714530931599464 386
0.5959186527582441 387
0.5647714514472667 388
0.43467755846083644 389
0.7343567712929087 390
0.5622026707008723 391
0.8082355234415374 392
0.3785261940481044 393
0.6367668701231886 394
0.7303975637848203 395
0.5506422667992849 396
0.5941423531836068 397
0.7003249041166559 398
0.7190952366541454 399
0.6332984076531964 400
0.5884207070981717 401
0.5586624136170235 402
0.47188942614212026 403
0.6155797743082658 404
0.6504013988202317 405
0.574563275574332 406
0.6631422182699913 407
0.6844591813642291 408
0.6685712368381627 409
0.6861809620025414 410
0.6551661250141274 411
0.6563906856831183 412
0.5172204196342414 413
0.5840060116097172 414
0.5545966187607133 415
0.4703098353163475 416
0.6928245536169544 417
0.6768312140258946 418
0.6702128491390209 419
0.6703514014912952 420
0.6646964761529467 421
0.6886343146254581 422
0.6500247135819359 423
0.628185039182614 424
0.5793689710265938 425
0.43460648641396915 426
0.7407225088724834 427
0.5300822143702807 428
0.6585944568509121 429
0.6815981787835212 430
0.774571695251632 431
0.6472009509195371 432
0.8457059012561223 433
0.6070928569224234 434
0.7763096119898374 435
0.5834897971507693 436
0.7060975479007643 437
0.6449218250640104 438
0.7164553067593833 439
0.6412368878543147 440
0.6707424049304609 441
0.5888021848989438 442
0.8022163666838086 443
0.7720577246760695 444
0.7426092980061625 445
0.7215365895371424 446
0.6240906927906877 447
0.5661459077573998 448
0.7531301289788755 449
0.7764757043928467 450
0.5497230190890452 451
0.5775080195308353 452
0.6333031699169267 453
0.6490683129554451 454
0.640373388831639 455
0.5001154622364761 456
0.5133047242467599 457
0.742725231983173 458
0.6464478082239539 459
0.7460968108371793 460
0.5490086807360186 461
0.5891680602589313 462
0.773318489506982 463
0.5096239214758277 464
0.6222397321173196 465
0.6797955420227421 466
0.5989924845690933 467
0.6808168195754604 468
0.6499513791917747 469
0.49057550593625443 470
0.5428246335561079 471
0.35083034616278086 472
0.7225174557580823 473
0.7031291590763904 474
0.7743415745267525 475
0.6185379669604052 476
0.6266998387042759 477
0.7329133176560831 478
0.5341704411755206 479
0.5773043133400994 480
0.600266741189873 481
0.6093144827133368 482
0.5348492312756437 483
0.5553401776149893 484
0.5177969821799173 485
0.6340228636437025 486
0.5806153727994809 487
0.7400523612380987 488
0.6327805820949264 489
0.49488702018281705 490
0.7762503095386587 491
0.6032630395443116 492
0.6247740007090302 493
0.6711122289571748 494
0.5868831956315944 495
0.7010716401126116 496
0.6498569099606533 497
0.6625432029481871 498
0.7793310805506639 499
0.6825623422672206 500
0.5996108721340782 501
0.5605338003591188 502
0.6312601234412798 503
0.5000844100276749 504
0.652574485690624 505
0.6720564269551852 506
0.7637754542828896 507
0.6871338890049421 508
0.6535172518210054 509
0.6423974233595697 510
0.6289698701799169 511
0.6376745875764909 512
0.7256045256165446 513
0.6604021636492741 514
0.7836016060534645 515
0.7193366339311691 516
0.7590948025077358 517
0.5945450822668743 518
0.6750954016309405 519
0.6941294394586305 520
0.6772477933473262 521
0.49798264137353254 522
0.5697533325952704 523
0.5324634711426061 524
0.4839352594486417 525
0.6351559252147158 526
0.6890267720662264 527
0.7635498521536781 528
0.6536058078360557 529
0.6277303999842448 530
0.5634339226470558 531
0.6366455040477079 532
0.7375394192059631 533
0.5087371121666737 534
0.5794101397396703 535
0.6378707471406821 536
0.5298673670612039 537
0.6776950690487635 538
0.5758311863555947 539
0.6923439572688472 540
0.6007479630650996 541
0.679022170540853 542
0.5428827651844024 543
0.6958772459465143 544
0.4634330348292337 545
0.7139001197336239 546
0.32349551830379664 547
0.7312973693168721 548
0.502036771952693 549
0.6214109806057933 550
0.6739569873627402 551
0.5334869134884346 552
0.7245118300922027 553
0.6237910982663918 554
0.7147271794005621 555
0.5554056987557413 556
0.5144460898348145 557
0.6955447100783995 558
0.7086488272497381 559
0.6402147457472809 560
0.4898633814235702 561
0.7054063234995787 562
0.5894121144896811 563
0.6591654834225076 564
0.6744959902661096 565
0.8058476269442524 566
0.660168799404973 567
0.7187213346704868 568
0.656315948580052 569
0.640346035236442 570
0.6471131068408411 571
0.68501943320405 572
0.6244041833004714 573
0.5746227374894795 574
0.6950908525240875 575
0.6786344633611716 576
0.7594158025029736 577
0.6666163760746033 578
0.6317935710140046 579
0.5933415283567414 580
0.6461129230793585 581
0.4971858856460327 582
0.6070040034501856 583
0.5219282161086334 584
0.5789376387446059 585
0.6937920611088029 586
0.6380343077181612 587
0.7001237188834047 588
0.6931587758358162 589
0.589613853767417 590
0.6971778834210502 591
0.7184435619713747 592
0.7177844949524907 593
0.6080060705311422 594
0.36843500719939615 595
0.5581886737458528 596
0.5620460226582105 597
0.5643338243449592 598
0.4836017592877714 599
0.520601909036016 600
0.57062314412116 601
0.7111534920882998 602
0.5858083105189922 603
0.5208569403187893 604
0.7394849574689798 605
0.4860208456484423 606
0.6077899189255362 607
0.6830944237756171 608
0.5924797568903368 609
0.503741866319345 610
0.5916159434104071 611
0.6184811168125165 612
0.5967613679456015 613
0.6679021724614079 614
0.5918355433427994 615
0.3712641921594322 616
0.5820940234468542 617
0.6802629302136666 618
0.6069615509839954 619
0.5097083153400968 620
0.7211793935054753 621
0.6030065263929456 622
0.5126282441053645 623
0.7560295480542806 624
0.595880713681622 625
0.6934811190490241 626
0.5129646088698299 627
0.6716333825085031 628
0.6444213917064177 629
0.5865133371616974 630
0.7423315255770468 631
0.7036440040934724 632
0.6432878690857264 633
0.516043621760645 634
0.5842714800657411 635
0.678954061506402 636
0.6658581428793702 637
0.7502173209099525 638
0.5433062530602963 639
0.5651080711199105 640
0.6711240983754169 641
0.6799225506976234 642
0.6024420865686864 643
0.48496921912974045 644
0.6955596371380334 645
0.5976667066979717 646
0.47749501923898596 647
0.6039819840507802 648
0.6484908068973942 649
0.6773701244307693 650
0.6153756119396969 651
0.7503716227894297 652
0.7690479564742826 653
0.6502214004016075 654
0.6499170573308479 655
0.5854185343026637 656
0.4607428317138187 657
0.6752814741948084 658
0.6821504662648222 659
0.7256059264961146 660
0.7687202450532246 661
0.5482915607120823 662
0.5151544583307905 663
0.47981647935129446 664
0.6709485697457123 665
0.620797815000086 666
0.6989540912395229 667
0.7160674934197228 668
0.7371368703511274 669
0.750408048346605 670
0.5285881635439451 671
0.6650656892333426 672
0.7328888091572108 673
0.6646522939547059 674
0.6286915371128862 675
0.6620522272329038 676
0.580544094651049 677
0.7178182542533155 678
0.6584680561940521 679
0.6211612580425392 680
0.5341078095589639 681
0.7208021923128907 682
0.6986235429739878 683
0.5897628016392906 684
0.6219794533075139 685
0.8314094710916703 686
0.6331105488784489 687
0.5682084226828434 688
0.7932082110104884 689
0.6068264700774753 690
0.6814867365595954 691
0.6493555026494239 692
0.6541366073798509 693
0.6936087454685118 694
0.7115344979702538 695
0.6608473156595109 696
0.5533643434665036 697
0.7516686959747855 698
0.6663287130464912 699
0.4769683790039032 700
0.703970319362559 701
0.569349854153731 702
0.7294056519207165 703
0.5353067806760579 704
0.6827143869429618 705
0.7276384534013076 706
0.6506307147043293 707
0.654967420199486 708
0.5332638888868795 709
0.6449180077721488 710
0.67828974439056 711
0.8112927234641926 712
0.8016138691504251 713
0.6574811589993625 714
0.6778560351554523 715
0.7205307277635675 716
0.7319862748600772 717
0.342157956744246 718
0.6459366388460294 719
0.5558849344541437 720
0.5874014887584791 721
0.6768858727320299 722
0.6850187785757647 723
0.6417853696358538 724
0.6219732055396946 725
0.6520431759801314 726
0.6891877163533686 727
0.5977147355611417 728
0.5800401351896509 729
0.7311636169497431 730
0.5285990463617949 731
0.794035778808259 732
0.6719937709316615 733
0.588918165828143 734
0.539719519523353 735
0.6129810097182005 736
0.5038430937469849 737
0.7121561986889431 738
0.5900917167733708 739
0.6287809940174569 740
0.5936889130466005 741
0.7512070611989259 742
0.7377803305145351 743
0.5899940154898805 744
0.613089620966345 745
0.6355443983815836 746
0.5530146610643747 747
0.5925678075312257 748
0.5104278521719328 749
0.5421742017307086 750
0.7059011137170863 751
0.7641006175290559 752
0.6888752015249358 753
0.7142823435628344 754
0.6199513838804112 755
0.6012121295581832 756
0.7817593823975543 757
0.6030104404897585 758
0.6332442245440728 759
0.6523195246784872 760
0.6657742978724444 761
0.7119968987268163 762
0.643066993547967 763
0.6178649740426384 764
0.6603847365753781 765
0.6257961439925633 766
0.6269433605808036 767
0.534414931949283 768
0.7578429211953058 769
0.6724888177214726 770
0.6976764695985096 771
0.6907323084617606 772
0.6079935264263288 773
0.557744135045614 774
0.5850865297787351 775
0.5658841507042611 776
0.3626629191973141 777
0.7044522471239911 778
0.669442716913278 779
0.6546782214619683 780
0.8251847678136841 781
0.7108848293472187 782
0.7833624172942832 783
0.6409217674936982 784
0.6341855709439319 785
0.6375290671661278 786
0.6629468480456234 787
0.7001428763936259 788
0.4309483209553463 789
0.7190150655200593 790
0.702849732596293 791
0.7349627348533597 792
0.7383327650018485 793
0.6578212312720373 794
0.5603501937162833 795
0.7151474799295314 796
0.6066251568139706 797
0.6344539450944935 798
0.7392934635214914 799
0.640662280241113 800
0.5072199929869678 801
0.613092229717225 802
0.6533081212544165 803
0.544804016553514 804
0.5976212011851172 805
0.6454587178934581 806
0.7460073804630084 807
0.3888163747012312 808
0.5655178651772834 809
0.5549881989414334 810
0.6485803311359102 811
0.6712870973101708 812
0.5258502189848162 813
0.788134825964515 814
0.627791219626793 815
0.5990356389331464 816
0.7028447534684152 817
0.6569188072845444 818
0.6534843553561328 819
0.5586351382782161 820
0.7774258067289344 821
0.6599073767154997 822
0.5951109709434372 823
0.44789727703342164 824
0.7354508786961548 825
0.6643146645502507 826
0.7601259187880416 827
0.653889119059629 828
0.6380225260382689 829
0.48146266817024874 830
0.7088480302880114 831
0.775228533354464 832
0.5773696354055919 833
0.7433050138823587 834
0.6403091177040254 835
0.5846089132403487 836
0.6388387861525615 837
0.657239094830399 838
0.5945764016047133 839
0.7293166571779215 840
0.7584263302697054 841
0.7251575848817073 842
0.7080810985332808 843
0.6551090668115114 844
0.4946328857451415 845
0.6089834157963299 846
0.6132967600018218 847
0.5751253750401567 848
0.6888946039024652 849
0.7278866964987165 850
0.6005440631468644 851
0.6351597920611435 852
0.622782414721728 853
0.5506788456909715 854
0.6258064942712213 855
0.542111034770432 856
0.502353129031959 857
0.7453819269468143 858
0.5257409493566068 859
0.7757921262002948 860
0.5784671886288342 861
0.6609374095384164 862
0.5780308753036774 863
0.6640093983802695 864
0.5523371273548746 865
0.6233613429061409 866
0.6024021267338762 867
0.5678898124848493 868
0.6332355438363295 869
0.574985978746158 870
0.46720102876045433 871
0.658005199022976 872
0.6209484314148456 873
0.6865225219299413 874
0.6563598823091727 875
0.6481739434589523 876

In [465]:
np.argmax(scores)

433

In [466]:
scores[np.argmax(scores)]

0.8457059012561223

In [470]:
scores[433]

0.8457059012561223

In [472]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=np.argmax(scores))
lr = LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
r2_score(y_test,y_pred)

0.8457059012561223

In [473]:
import pickle

In [474]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [475]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']], columns=['name','company','year','kms_driven','fuel_type']))

array([458894.10960853])